# SoilHarmony project

**Copy-paste uit email Hans Van Calster:**

Het SoilHarmony project is een Europees Horizon project dat gegund is aan een consortium waar INBO deel van uitmaakt. Momenteel zitten we in de fase waarin de Grant Agreement wordt opgemaakt en onderhandeld. Het project zal starten in juni. Ons team zal in dit project een werkpakket trekken. We gaan statistische onderbouwing geven aan de ontwikkeling, validatie en gebruik van transferfuncties of overdrachtsfuncties, o.a. via de ontwikkeling van een R pakket. Het project moet onderbouwing geven aan wat in de soil monitoring law in deel B van Annex II staat https://eur-lex.europa.eu/legal-content/NL/TXT/HTML/?uri=OJ:L_202502360#anx_II:
Deel B: methoden voor het bepalen of ramen van de waarden van de bodemdescriptoren

Aan de begrippen "gelijkwaardig", "gevalideerd" en  "overdrachtsfunctie"  gaan we dus een statistische onderbouwing moeten geven. Een overdrachtsfunctie kan je zien als een functie (bv een regressievergelijking) die metingen van een niet-referentiemethode omzet naar de referentiemethode (lees: je maakt predicties op basis van een statistisch model voor data die je model niet gezien heeft). Volgens mij kan je voor deze doelstelling perfect verder met lineaire modellen (en uitbreidingen ervan zoals GL(M)M), maar we moeten toch eens nadenken of alternatieven al dan niet (beter? slechter?) beantwoorden aan de doelstelling. Ik denk dat het hiervoor relevant is om bij te lezen over het topic "regression dilution". Bijgevoegd zijn twee papers (uit heel andere domeinen) die hier dieper op ingaan en goed aangeven wanneer je beter deze alternatieven verkiest boven lineaire modellen. Mijn collega Bruno De Vos verwees me naar het mcr R package waar een aantal van deze alternatieve methoden geïmplementeerd zijn. Zie https://cran.r-project.org/web/packages/mcr/refman/mcr.html#topic+mcreg  Je zal zien dat er een fundamenteel verschil is tussen de methoden die de error in beide richtingen (x en y as) beschouwen versus de methoden die enkel de error in de y richting beschouwen (zoals lineaire regressiemodellen).